In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import datetime
%matplotlib inline

In [2]:
accern_data = pd.read_csv("C:/Users/zhang/Desktop/NYU/2019 Fall/DS-GA-1006/Accern/Code/accern_data.csv")
price_data = pd.read_csv("C:/Users/zhang/Desktop/NYU/2019 Fall/DS-GA-1006/Accern/Code/price.csv")

In [3]:
accern_data = accern_data[accern_data['ticker'] != 'NFX']
price_data = price_data[price_data['ticker'] != 'NFX']

In [5]:
# price_data[price_data['ticker'] == 'AAPL']

,date,ticker,adj_close,close,high,low,open,volume
0,2014-01-02,AAPL,71.32,79.02,79.58,78.86,79.38,58671200.0
20,2014-01-03,AAPL,69.75,77.28,79.10,77.20,78.98,98116900.0
40,2014-01-06,AAPL,70.13,77.70,78.11,76.23,76.78,103152700.0
60,2014-01-07,AAPL,69.63,77.15,77.99,76.85,77.76,79302300.0
80,2014-01-08,AAPL,70.07,77.64,77.94,76.96,76.97,64632400.0
100,2014-01-09,AAPL,69.18,76.65,78.12,76.48,78.11,69787200.0
120,2014-01-10,AAPL,68.72,76.13,77.26,75.87,77.12,76244000.0
140,2014-01-13,AAPL,69.08,76.53,77.50,75.70,75.70,94623200.0
160,2014-01-14,AAPL,70.45,78.06,78.10,76.81,76.89,83140400.0
180,2014-01-15,AAPL,71.87,79.62,80.03,78.81,79.07,97909700.0
200,2014-01-16,AAPL,71.47,79.18,79.55,78.81,79.27,57319500.0
220,2014-01-17,AAPL,69.71,77.24,78.87,77.13,78.78,106684900.0
240,2014-01-21,AAPL,70.80,78.44,78.58,77.20,77.28,82131700.0
260,2014-01-22,AAPL,71.11,78.79,79.61,78.26,78.70,94996300.0
280,2014-01-23,AAPL,71.71,79.45,79.50,77.83,78.56,100809800.0
300,2014-01-24,AAPL,70.41,78.01,79.37,77.82,79.14,107338700.0
320,2014-01-27,AAPL,70.98,78.64,79.26,77.96,78.58,138719700.0
340,2014-01-28,AAPL,65.31,72.36,73.57,71.72,72.68,266380800.0
360,2014-01-29,AAPL,64.57,71.54,72.48,71.23,71.99,125702500.0
380,2014-01-30,AAPL,64.44,71.40,72.36,70.96,71.79,169625400.0
400,2014-01-31,AAPL,64.55,71.51,71.65,70.51,70.74,116199300.0
420,2014-02-03,AAPL,64.67,71.65,72.53,71.33,71.80,100366000.0
440,2014-02-04,AAPL,65.60,72.68,72.78,71.82,72.26,94170300.0
460,2014-02-05,AAPL,66.09,73.23,73.61,72.32,72.37,82086200.0
480,2014-02-06,AAPL,66.48,73.22,73.36,72.54,72.87,64441300.0
500,2014-02-07,AAPL,67.41,74.24,74.70,73.91,74.48,92570100.0
520,2014-02-10,AAPL,68.62,75.57,76.00,74.00,74.09,86389800.0
540,2014-02-11,AAPL,69.52,76.57,76.82,75.64,75.80,70564200.0
560,2014-02-12,AAPL,69.52,76.56,77.08,76.18,76.71,77025200.0
580,2014-02-13,AAPL,70.62,77.78,77.84,76.31,76.38,76849500.0
...,...,...,...,...,...,...,...,...
23120,2018-08-03,AAPL,204.10,207.99,208.74,205.48,207.03,33447400.0
23140,2018-08-06,AAPL,205.16,209.07,209.25,207.07,208.00,25425400.0
23160,2018-08-07,AAPL,203.23,207.11,209.50,206.76,209.32,25587400.0
23180,2018-08-08,AAPL,203.37,207.25,207.81,204.52,206.05,22525500.0
23200,2018-08-09,AAPL,204.97,208.88,209.78,207.20,209.53,23492600.0
23220,2018-08-10,AAPL,204.36,207.53,209.10,206.67,207.36,24611200.0
23240,2018-08-13,AAPL,205.68,208.87,210.95,207.70,209.31,25890900.0
23260,2018-08-14,AAPL,206.54,209.75,210.56,208.26,210.16,20748000.0
23280,2018-08-15,AAPL,207.03,210.24,210.74,208.33,209.22,28807600.0
23300,2018-08-16,AAPL,210.06,213.32,213.81,211.47,211.75,28500400.0
23320,2018-08-17,AAPL,214.26,217.58,217.95,213.16,213.44,35427000.0
23340,2018-08-20,AAPL,212.17,215.46,219.18,215.11,218.10,30287700.0
23360,2018-08-21,AAPL,211.75,215.04,217.19,214.03,216.80,26159800.0
23380,2018-08-22,AAPL,211.76,215.05,216.36,213.84,214.10,19018100.0
23400,2018-08-23,AAPL,212.20,215.49,217.05,214.60,214.65,18883200.0
23420,2018-08-24,AAPL,212.86,216.16,216.90,215.11,216.60,18476400.0
23440,2018-08-27,AAPL,214.61,217.94,218.74,216.33,217.15,20525100.0
23460,2018-08-28,AAPL,216.34,219.70,220.54,218.92,219.01,22776800.0
23480,2018-08-29,AAPL,219.57,222.98,223.49,219.41,220.15,27254800.0
23500,2018-08-30,AAPL,221.59,225.03,228.26,222.40,223.25,48793800.0
23520,2018-08-31,AAPL,224.15,227.63,228.87,226.00,226.51,43340100.0
23540,2018-09-04,AAPL,224.87,228.36,229.18,226.63,228.41,27390100.0
23560,2018-09-05,AAPL,223.40,226.87,229.67,225.10,228.99,33333000.0
23580,2018-09-06,AAPL,219.69,223.10,227.35,221.30,226.23,34290000.0
23600,2018-09-07,AAPL,217.92,221.30,225.37,220.71,221.85,37619800.0
23620,2018-09-10,AAPL,214.99,218.33,221.85,216.47,220.95,39516500.0
23640,2018-09-11,AAPL,220.43,223.85,224.30,216.56,218.01,35749000.0
23660,2018-09-12,AAPL,217.69,221.07,225.00,219.84,224.94,49278700.0
23680,2018-09-13,AAPL,222.95,226.41,228.35,222.57,223.52,41706400.0
23700,2018-09-14,AAPL,220.42,223.84,226.84,222.52,225.75,31999300.0

In [4]:
accern_data.shape

(201637, 144)

In [5]:
price_data.shape

(22534, 8)

In [6]:
accern_data.head()

,date,ticker,entity_share_class_figi,event_impact_gt_mu_pos_add_sigma_pos_avg,event_impact_gt_mu_pos_add_sigma_pos_sum,event_impact_gt_mu_pos_add_sigma_pos_min,event_impact_gt_mu_pos_add_sigma_pos_max,event_impact_lt_mu_sub_sigma_avg,event_impact_lt_mu_sub_sigma_sum,event_impact_lt_mu_sub_sigma_min,...,overall_author_republish_score_max,event_sentiment_avg,event_sentiment_sum,event_sentiment_min,event_sentiment_max,entity_relevance_avg,entity_relevance_sum,entity_relevance_min,entity_relevance_max,count
0,2014-01-02 09:00:00-05,GOOG,BBG009S3NB21,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.8943,43.555556,392.00,8.0,87.5,100.000000,900.0,100.0,100.0,9
1,2014-01-02 10:00:00-05,AAPL,BBG001S5N8V8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.2202,14.400000,28.80,-31.6,60.4,100.000000,200.0,100.0,100.0,2
2,2014-01-02 10:00:00-05,BA,BBG001S5P0V3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.5262,14.750000,29.50,0.0,29.5,100.000000,200.0,100.0,100.0,2
3,2014-01-02 10:00:00-05,GOOG,BBG009S3NB21,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.9396,4.012105,76.23,-91.7,89.6,98.947368,1880.0,90.0,100.0,19
4,2014-01-02 11:00:00-05,BA,BBG001S5P0V3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.4995,47.575000,190.30,0.0,87.5,100.000000,400.0,100.0,100.0,4

In [7]:
accern_data['ticker'].unique()

array(['GOOG', 'AAPL', 'BA', 'NVDA', 'TSS', 'AMZN', 'CAT', 'UAL', 'PFE',
       'FE', 'ABC', 'ALL', 'UNH', 'GT', 'L', 'APH', 'MTD', 'TROW', 'MCO'],
      dtype=object)

In [8]:
price_data.head()

         date ticker  adj_close   close    high     low    open      volume
0  2014-01-02   AAPL      71.32   79.02   79.58   78.86   79.38  58671200.0
1  2014-01-02    ABC      63.80   69.89   70.23   69.48   70.11   1148400.0
2  2014-01-02    ALL      48.04   53.55   54.45   53.50   54.09   1909100.0
3  2014-01-02   AMZN     397.97  397.97  399.36  394.02  398.80   2137800.0
4  2014-01-02    APH      41.28   43.87   44.40   43.73   44.37    883600.0

In [9]:
# Check missing values

null_accern_data = accern_data[accern_data.isnull().any(axis = 1)]
null_price_data = price_data[price_data.isnull().any(axis=1)]

In [10]:
# No missing values in accern data, missing values for on particular ticker for price data

In [11]:
accern_data['date_time'] = pd.to_datetime(accern_data['date'], utc = True).dt.tz_convert('US/Eastern')
accern_data['day'] = accern_data['date_time'].dt.date
accern_data['hour'] = accern_data['date_time'].dt.hour
accern_data['week'] = accern_data['date_time'].dt.dayofweek

In [12]:
accern_data = accern_data.sort_values(['ticker', 'date', 'hour'])

In [13]:
full_data = pd.DataFrame(columns = ['ticker', 'day', 'hour'])

In [14]:
ticker_list = []
for ticker in accern_data['ticker'].unique():
    ticker_list.extend([ticker] * 1718 * 24)

In [15]:
day_list = []
for day in sorted(accern_data['day'].unique()):
    day_list.extend([day] * 24)
day_list = day_list * 19

In [16]:
hour_list = sorted(accern_data['hour'].unique()) * 1718 * 19

In [17]:
full_time = pd.DataFrame({'ticker' : ticker_list, 'day' : day_list, 'hour' : hour_list})

In [18]:
full_time['dayofwork'] = pd.to_datetime(full_time['day']).dt.dayofweek + 1

In [19]:
full_data = accern_data.drop('week', axis = 1).merge(full_time, how = 'right', on = ['ticker', 'day', 'hour'])

In [20]:
full_data = full_data.sort_values(['ticker', 'day', 'hour'])
full_data = full_data.drop(['date', 'entity_share_class_figi', 'date_time'], axis = 1)

## Ffill

In [21]:
full_data_ffill = full_data.fillna(method = 'ffill')

In [22]:
full_data_ffill = full_data_ffill[full_data_ffill['day'] != datetime.date(2014,1,2)]
full_data_ffill.reset_index(inplace = True, drop = True)

In [53]:
full_data_ffill = full_data_ffill[~full_data_ffill['day'].isin([datetime.date(2014,1,2), datetime.date(2018,9,13),\
                                                                datetime.date(2018,9,14), datetime.date(2018,9,15)])]

In [58]:
full_data_ffill.to_csv('unagg_ffill_news.csv')

In [24]:
#aggregation

full_data_ffill_copy = full_data_ffill.copy()

In [25]:
full_data_ffill_copy.loc[full_data_ffill_copy['dayofwork'] == 6, 'day'] = \
full_data_ffill_copy.loc[full_data_ffill_copy['dayofwork'] == 6, 'day'] - pd.Timedelta(days = 1)

full_data_ffill_copy.loc[full_data_ffill_copy['dayofwork'] == 7, 'day'] = \
full_data_ffill_copy.loc[full_data_ffill_copy['dayofwork'] == 7, 'day'] - pd.Timedelta(days = 2)

full_data_ffill_copy.loc[full_data_ffill_copy['dayofwork'] == 6, 'hour'] = 8
full_data_ffill_copy.loc[full_data_ffill_copy['dayofwork'] == 7, 'hour'] = 8

In [26]:
full_data_ffill_copy['day'] = np.where((full_data_ffill_copy['hour'] <= 7) & (full_data_ffill_copy['dayofwork'] != 1), \
                                       full_data_ffill_copy['day'] - pd.Timedelta(days = 1), \
                                       full_data_ffill_copy['day'])

full_data_ffill_copy['day'] = np.where((full_data_ffill_copy['hour'] <= 7) & (full_data_ffill_copy['dayofwork'] == 1), \
                                       full_data_ffill_copy['day'] - pd.Timedelta(days = 3), \
                                       full_data_ffill_copy['day'])

In [27]:
full_data_ffill_copy.drop(['hour', 'dayofwork'], axis = 1, inplace = True)

In [28]:
full_data_ffill_copy = full_data_ffill_copy.groupby(['ticker', 'day'], as_index = False).mean()

In [29]:
full_data_ffill_copy = full_data_ffill_copy[full_data_ffill_copy['day'] != datetime.date(2014, 1, 2)]

In [30]:
full_data_ffill_copy.to_csv('agg_ffill_news.csv')

In [31]:
full_data_ffill_copy

,ticker,day,event_impact_gt_mu_pos_add_sigma_pos_avg,event_impact_gt_mu_pos_add_sigma_pos_sum,event_impact_gt_mu_pos_add_sigma_pos_min,event_impact_gt_mu_pos_add_sigma_pos_max,event_impact_lt_mu_sub_sigma_avg,event_impact_lt_mu_sub_sigma_sum,event_impact_lt_mu_sub_sigma_min,event_impact_lt_mu_sub_sigma_max,...,overall_author_republish_score_max,event_sentiment_avg,event_sentiment_sum,event_sentiment_min,event_sentiment_max,entity_relevance_avg,entity_relevance_sum,entity_relevance_min,entity_relevance_max,count
1,AAPL,2014-01-03,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,1.291328,-4.109028,-10.747222,-7.577778,-0.856944,100.000000,131.944444,100.000000,100.000000,1.319444
2,AAPL,2014-01-06,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,1.129596,7.295486,5.856250,-4.450000,17.606250,99.583333,132.500000,99.166667,100.000000,1.333333
3,AAPL,2014-01-07,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,2.417688,12.192708,12.291667,-0.612500,25.518750,94.861111,177.500000,94.166667,95.416667,1.833333
4,AAPL,2014-01-08,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,1.559596,23.502500,33.509167,17.759167,29.245833,97.291667,120.833333,97.083333,97.500000,1.250000
5,AAPL,2014-01-09,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,5.172796,10.022708,24.850417,-8.362083,30.904167,94.520833,193.750000,93.750000,95.833333,2.041667
6,AAPL,2014-01-10,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,4.811521,45.444618,104.034028,37.541667,51.848611,97.596451,198.472222,96.527778,98.472222,2.027778
7,AAPL,2014-01-13,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,2.742042,14.622222,38.075000,7.937500,22.562500,92.847222,157.083333,92.500000,93.333333,1.708333
8,AAPL,2014-01-14,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,1.045821,-3.382639,-6.106250,-13.727083,2.854167,94.444444,139.166667,93.333333,95.000000,1.458333
9,AAPL,2014-01-15,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,2.128771,28.225000,37.700000,17.187500,40.758333,97.291667,150.416667,96.666667,97.916667,1.541667
10,AAPL,2014-01-16,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,1.642071,4.359583,-0.051667,-11.029167,19.748333,97.083333,126.250000,97.083333,97.083333,1.291667
11,AAPL,2014-01-17,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,0.787192,17.583333,29.070833,15.155556,19.519444,99.583333,117.638889,99.583333,99.583333,1.180556
12,AAPL,2014-01-20,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,1.234492,60.377500,56.948333,60.073333,60.681667,100.000000,104.166667,100.000000,100.000000,1.041667
13,AAPL,2014-01-21,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,1.065254,8.297222,27.345833,-9.520833,26.462500,97.638889,167.916667,97.083333,97.916667,1.708333
14,AAPL,2014-01-22,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,1.132892,16.882222,25.405417,7.029167,27.609583,96.527778,154.583333,96.250000,96.666667,1.583333
15,AAPL,2014-01-23,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,3.338071,-7.469479,-21.836250,-21.902917,10.472917,95.319444,194.166667,94.166667,96.666667,2.041667
16,AAPL,2014-01-24,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,1.966115,-4.445185,-13.612083,-14.302778,4.445833,96.986111,159.861111,96.250000,97.500000,1.638889
17,AAPL,2014-01-27,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,3.379179,3.386316,18.615000,-24.049167,31.380833,96.867452,432.083333,94.166667,98.333333,4.416667
18,AAPL,2014-01-28,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,2.386904,-6.240313,-18.870833,-46.820833,34.383333,98.866071,407.500000,95.416667,100.000000,4.125000
19,AAPL,2014-01-29,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,3.459767,-4.674375,-32.098750,-19.504167,18.562500,92.475198,242.083333,91.666667,92.916667,2.583333
20,AAPL,2014-01-30,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,1.321571,24.356250,17.791667,16.500000,30.804167,96.180556,136.250000,94.583333,97.500000,1.416667
21,AAPL,2014-01-31,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,0.518514,23.598900,32.772222,4.614583,43.479167,99.097222,147.916667,98.888889,99.305556,1.500000
22,AAPL,2014-02-03,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,0.624133,9.067569,25.695833,-1.329167,20.575000,98.750000,202.083333,97.916667,99.583333,2.041667
23,AAPL,2014-02-04,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,1.045512,7.404167,4.704167,-8.316667,19.687500,98.472222,202.083333,97.916667,98.750000,2.041667
24,AAPL,2014-02-05,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,1.338508,7.425694,13.254167,-0.687500,17.462500,96.736111,144.583333,96.250000,97.500000,1.500000
25,AAPL,2014-02-06,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,2.318588,-7.842181,-16.846667,-32.287500,17.391667,93.576389,288.333333,92.083333,95.416667,3.083333
26,AAPL,2014-02-07,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,1.359639,1.446667,6.518056,-5.052778,7.604167,94.500000,135.694444,94.166667,94.722222,1.430556
27,AAPL,2014-02-10,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,1.949696,0.760417,4.041667,-12.912500,13.204167,97.500000,155.833333,97.500000,97.500000,1.583333
28,AAPL,2014-02-11,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,2.479142,15.391111,40.408333,-0.187500,30.991667,97.333333,198.750000,95.833333,97.916667,2.041667
29,AAPL,2014-02-12,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,1.431942,13.890694,39.507500,-0.939583,27.133333,97.152778,173.333333,96.250000,97.916667,1.791667
30,AAPL,2014-02-13,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,1.569708,11.493056,23.129167,-12.879167,35.920833,99.166667,194.583333,98.750000,99.583333,1.958333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23283,UNH,2018-08-06,0.0,0.0,0.0,0.0,54.166667,108.333333,54.166667,54.166667,...,0.069342,-2.112496,11.400008,-5.287492,1.062500,100.000000,162.500000,100.000000,100.000000,1.625000
23284,UNH,2018-08-07,0.0,0.0,0.0,0.0,11.111111,16.666667,8.333333,16.666667,...,0.098400,62.197914,98.708325,55.995833,66.408325,100.000000,175.000000,100.000000,100.000000,1.750000
23285,UNH,2018-08-08,0.0,0.0,0.0,0.0,12.500000,25.000000,4.166667,25.000000,...,0.057667,30.496233,45.079567,20.079567,37.525400,100.000000,133.333333,100.000000,100.000000,1.333333
23286,UNH,2018-08-09,0.0,0.0,0.0,0.0,12.500000,25.000000,0.000000,25.000000,...,0.035421,25.650000,36.600000,14.725000,36.575000,97.916667,127.083333,97.916667,97.916667,1.291667
23287,UNH,2018-08-10,0.0,0.0,0.0,0.0,15.277778,33.333333,6.944444,30.555556,...,0.123742,44.161111,87.569444,26.119444,53.781944,100.000000,183.333333,100.000000,100.000000,1.833333
23288,UNH,2018-08-13,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,0.071071,52.866667,59.116667,52.866667,52.866667,100.000000,108.333333,100.000000,100.000000,1.083333
23289,UNH,2018-08-14,0.0,0.0,0.0,0.0,2.777778,8.333333,0.000000,4.166667,...,0.033675,38.269787,55.941658,30.624992,47.691667,100.000000,154.166667,100.000000,100.000000,1.541667
23290,UNH,2018-08-15,0.0,0.0,0.0,0.0,8.680556,29.166667,0.000000,29.166667,...,0.038767,71.432639,119.391667,66.266667,73.425000,100.000000,170.833333,100.000000,100.000000,1.708333
23291,UNH,2018-08-16,0.0,0.0,0.0,0.0,6.250000,25.000000,0.000000,25.000000,...,0.066929,59.512500,111.175000,52.425000,61.875000,100.000000,195.833333,100.000000,100.000000,1.958333
23292,UNH,2018-08-17,0.0,0.0,0.0,0.0,8.719136,29.166667,5.555556,12.500000,...,0.054919,34.527778,68.565278,16.723611,51.437500,100.000000,180.555556,100.000000,100.000000,1.805556
23293,UNH,2018-08-20,0.0,0.0,0.0,0.0,10.000000,41.666667,8.333333,12.500000,...,0.041158,26.420833,42.395833,18.437500,37.704167,100.000000,162.500000,100.000000,100.000000,1.625000
23294,UNH,2018-08-21,0.0,0.0,0.0,0.0,2.083333,4.166667,0.000000,4.166667,...,0.038883,58.313887,74.495829,57.937500,58.870829,100.000000,120.833333,100.000000,100.000000,1.208333
23295,UNH,2018-08-22,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,0.106608,-6.383333,2.991667,-6.383333,-6.383333,100.000000,112.500000,100.000000,100.000000,1.125000
23296,UNH,2018-08-23,0.0,0.0,0.0,0.0,5.833333,25.000000,4.166667,12.500000,...,0.175821,43.367500,113.029167,6.554167,75.920833,100.000000,245.833333,100.000000,100.000000,2.458333
23297,UNH,2018-08-24,0.0,0.0,0.0,0.0,45.787037,156.944444,29.166667,75.000000,...,0.095436,31.654859,88.808328,3.854165,56.104165,100.000000,311.111111,100.000000,100.000000,3.111111
23298,UNH,2018-08-27,0.0,0.0,0.0,0.0,12.500000,37.500000,12.500000,12.500000,...,0.124675,55.595694,70.792917,51.655417,58.409583,98.194444,143.750000,97.916667,98.333333,1.458333
23299,UNH,2018-08-28,0.0,0.0,0.0,0.0,2.083333,16.666667,0.000000,4.166667,...,0.168517,35.369271,93.129167,34.058333,35.979167,100.000000,179.166667,100.000000,100.000000,1.791667
23300,UNH,2018-08-29,0.0,0.0,0.0,0.0,5.000000,25.000000,0.000000,8.333333,...,0.009692,40.883333,55.933333,37.766667,45.050000,100.000000,141.666667,100.000000,100.000000,1.416667
23301,UNH,2018-08-30,0.0,0.0,0.0,0.0,5.000000,25.000000,0.000000,8.333333,...,0.024479,61.085417,82.700000,55.625000,67.337500,100.000000,158.333333,100.000000,100.000000,1.583333
23302,UNH,2018-08-31,0.0,0.0,0.0,0.0,0.925926,4.166667,0.000000,2.777778,...,0.043653,74.138704,119.181944,72.669444,75.154167,100.000000,165.277778,100.000000,100.000000,1.652778
23303,UNH,2018-09-03,0.0,0.0,0.0,0.0,79.861111,83.333333,79.166667,83.333333,...,0.030200,66.198611,79.483333,65.262500,66.666667,100.000000,120.833333,100.000000,100.000000,1.208333
23304,UNH,2018-09-04,0.0,0.0,0.0,0.0,2.083333,4.166667,0.000000,4.166667,...,0.005625,28.945329,64.789600,8.462517,37.512517,99.583333,228.750000,99.583333,99.583333,2.291667
23305,UNH,2018-09-05,0.0,0.0,0.0,0.0,12.500000,25.000000,12.500000,12.500000,...,0.076758,22.860417,51.504167,22.341667,23.379167,100.000000,137.500000,100.000000,100.000000,1.375000
23306,UNH,2018-09-06,0.0,0.0,0.0,0.0,18.750000,33.333333,12.500000,25.000000,...,0.051150,34.383333,59.383333,34.383333,34.383333,100.000000,133.333333,100.000000,100.000000,1.333333
23307,UNH,2018-09-07,0.0,0.0,0.0,0.0,4.050926,13.888889,0.000000,9.722222,...,0.017289,69.634028,100.558333,65.005556,73.294444,100.000000,154.166667,100.000000,100.000000,1.541667
23308,UNH,2018-09-10,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,0.175592,61.412500,87.620833,50.120833,67.058333,100.000000,150.000000,100.000000,100.000000,1.500000
23309,UNH,2018-09-11,0.0,0.0,0.0,0.0,4.166667,4.166667,4.166667,4.166667,...,0.110342,4.166667,4.166667,4.166667,4.166667,100.000000,100.000000,100.000000,100.000000,1.000000
23310,UNH,2018-09-12,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,0.322758,-23.866667,-23.866667,-23.866667,-23.866667,100.000000,100.000000,100.000000,100.000000,1.000000
23311,UNH,2018-09-13,0.0,0.0,0.0,0.0,2.083333,4.166667,0.000000,4.166667,...,0.016946,39.628750,106.825833,14.221667,62.625000,100.000000,258.333333,100.000000,100.000000,2.583333
23312,UNH,2018-09-14,0.0,0.0,0.0,0.0,1.875000,5.000000,0.000000,5.000000,...,0.073177,64.147125,80.734250,58.961750,69.152500,100.000000,140.000000,100.000000,100.000000,1.400000

In [32]:
price_ticker_list = []
for ticker in price_data['ticker'].unique():
    price_ticker_list.extend([ticker] * 1226)

In [33]:
price_date_list = sorted(full_data_ffill_copy['day'].unique()) *  19

price_full_time = pd.DataFrame({'ticker' : price_ticker_list, 'date' : price_date_list})

In [34]:
price_full_time['day'] = price_full_time['date'].astype('str')

In [35]:
price_full_data = price_data.merge(price_full_time, how = 'right', left_on = ['ticker', 'date'], right_on = ['ticker', 'day'])

price_full_data = price_full_data.sort_values(['ticker', 'day'])

price_full_data.reset_index(inplace = True, drop = True)

In [36]:
price_data_ffill = price_full_data.fillna(method = 'ffill')

In [39]:
price_data_ffill['open_price_change'] = (price_data_ffill['open'].shift(-2) - price_data_ffill['open'].shift(-1))\
                                        / price_data_ffill['open'].shift(-1)

In [41]:
price_data_ffill.sort_values(['ticker', 'day'], inplace = True)
price_data_ffill = price_data_ffill[~price_data_ffill['day'].isin(['2014-01-02', '2018-09-13', '2018-09-14'])]

In [45]:
price_data_ffill.head()

,date_x,ticker,adj_close,close,high,low,open,volume,date_y,day,open_price_change
0,2014-01-03,AAPL,69.75,77.28,79.10,77.20,78.98,98116900.0,2014-01-03,2014-01-03,0.012764
1,2014-01-06,AAPL,70.13,77.70,78.11,76.23,76.78,103152700.0,2014-01-06,2014-01-06,-0.010159
2,2014-01-07,AAPL,69.63,77.15,77.99,76.85,77.76,79302300.0,2014-01-07,2014-01-07,0.014811
3,2014-01-08,AAPL,70.07,77.64,77.94,76.96,76.97,64632400.0,2014-01-08,2014-01-08,-0.012674
4,2014-01-09,AAPL,69.18,76.65,78.12,76.48,78.11,69787200.0,2014-01-09,2014-01-09,-0.018413
5,2014-01-10,AAPL,68.72,76.13,77.26,75.87,77.12,76244000.0,2014-01-10,2014-01-10,0.015720
6,2014-01-13,AAPL,69.08,76.53,77.50,75.70,75.70,94623200.0,2014-01-13,2014-01-13,0.028352
7,2014-01-14,AAPL,70.45,78.06,78.10,76.81,76.89,83140400.0,2014-01-14,2014-01-14,0.002529
8,2014-01-15,AAPL,71.87,79.62,80.03,78.81,79.07,97909700.0,2014-01-15,2014-01-15,-0.006181
9,2014-01-16,AAPL,71.47,79.18,79.55,78.81,79.27,57319500.0,2014-01-16,2014-01-16,0.000000
10,2014-01-17,AAPL,69.71,77.24,78.87,77.13,78.78,106684900.0,2014-01-17,2014-01-17,-0.019040
11,2014-01-17,AAPL,69.71,77.24,78.87,77.13,78.78,106684900.0,2014-01-20,2014-01-20,0.018375
12,2014-01-21,AAPL,70.80,78.44,78.58,77.20,77.28,82131700.0,2014-01-21,2014-01-21,-0.001779
13,2014-01-22,AAPL,71.11,78.79,79.61,78.26,78.70,94996300.0,2014-01-22,2014-01-22,0.007383
14,2014-01-23,AAPL,71.71,79.45,79.50,77.83,78.56,100809800.0,2014-01-23,2014-01-23,-0.007076
15,2014-01-24,AAPL,70.41,78.01,79.37,77.82,79.14,107338700.0,2014-01-24,2014-01-24,-0.075083
16,2014-01-27,AAPL,70.98,78.64,79.26,77.96,78.58,138719700.0,2014-01-27,2014-01-27,-0.009494
17,2014-01-28,AAPL,65.31,72.36,73.57,71.72,72.68,266380800.0,2014-01-28,2014-01-28,-0.002778
18,2014-01-29,AAPL,64.57,71.54,72.48,71.23,71.99,125702500.0,2014-01-29,2014-01-29,-0.014626
19,2014-01-30,AAPL,64.44,71.40,72.36,70.96,71.79,169625400.0,2014-01-30,2014-01-30,0.014984
20,2014-01-31,AAPL,64.55,71.51,71.65,70.51,70.74,116199300.0,2014-01-31,2014-01-31,0.006407
21,2014-02-03,AAPL,64.67,71.65,72.53,71.33,71.80,100366000.0,2014-02-03,2014-02-03,0.001522
22,2014-02-04,AAPL,65.60,72.68,72.78,71.82,72.26,94170300.0,2014-02-04,2014-02-04,0.006909
23,2014-02-05,AAPL,66.09,73.23,73.61,72.32,72.37,82086200.0,2014-02-05,2014-02-05,0.022094
24,2014-02-06,AAPL,66.48,73.22,73.36,72.54,72.87,64441300.0,2014-02-06,2014-02-06,-0.005236
25,2014-02-07,AAPL,67.41,74.24,74.70,73.91,74.48,92570100.0,2014-02-07,2014-02-07,0.023080
26,2014-02-10,AAPL,68.62,75.57,76.00,74.00,74.09,86389800.0,2014-02-10,2014-02-10,0.012005
27,2014-02-11,AAPL,69.52,76.57,76.82,75.64,75.80,70564200.0,2014-02-11,2014-02-11,-0.004302
28,2014-02-12,AAPL,69.52,76.56,77.08,76.18,76.71,77025200.0,2014-02-12,2014-02-12,0.014664
29,2014-02-13,AAPL,70.62,77.78,77.84,76.31,76.38,76849500.0,2014-02-13,2014-02-13,0.000000
...,...,...,...,...,...,...,...,...,...,...,...
23262,2018-08-02,UNH,251.14,256.08,256.30,252.23,253.50,1854400.0,2018-08-02,2018-08-02,0.000195
23263,2018-08-03,UNH,252.25,257.22,257.56,254.30,256.45,1422300.0,2018-08-03,2018-08-03,0.004444
23264,2018-08-06,UNH,251.80,256.76,257.54,255.47,256.50,1398100.0,2018-08-06,2018-08-06,0.001824
23265,2018-08-07,UNH,252.68,257.65,258.84,257.13,257.64,1462800.0,2018-08-07,2018-08-07,0.006974
23266,2018-08-08,UNH,253.81,258.81,259.50,257.92,258.11,1494300.0,2018-08-08,2018-08-08,0.002232
23267,2018-08-09,UNH,256.54,261.59,263.02,259.31,259.91,2315000.0,2018-08-09,2018-08-09,0.001958
23268,2018-08-10,UNH,255.33,260.36,261.50,259.11,260.49,1625000.0,2018-08-10,2018-08-10,-0.000421
23269,2018-08-13,UNH,255.87,260.91,262.55,260.30,261.00,1635100.0,2018-08-13,2018-08-13,0.004178
23270,2018-08-14,UNH,258.39,263.48,264.30,260.85,260.89,1941600.0,2018-08-14,2018-08-14,-0.001565
23271,2018-08-15,UNH,255.58,260.61,262.69,259.19,261.98,2017700.0,2018-08-15,2018-08-15,0.007570
23272,2018-08-16,UNH,258.02,263.10,263.75,261.45,261.57,2115900.0,2018-08-16,2018-08-16,-0.002087
23273,2018-08-17,UNH,257.27,262.33,264.13,261.72,263.55,1969700.0,2018-08-17,2018-08-17,-0.004373
23274,2018-08-20,UNH,257.33,262.40,263.49,261.57,263.00,1786200.0,2018-08-20,2018-08-20,0.000382
23275,2018-08-21,UNH,256.64,261.69,262.52,260.73,261.85,1559300.0,2018-08-21,2018-08-21,-0.003550
23276,2018-08-22,UNH,255.71,260.74,261.95,260.25,261.95,2148500.0,2018-08-22,2018-08-22,0.002797
23277,2018-08-23,UNH,256.37,261.42,262.56,259.56,261.02,1603500.0,2018-08-23,2018-08-23,0.012416
23278,2018-08-24,UNH,259.18,264.28,264.78,261.75,261.75,2238600.0,2018-08-24,2018-08-24,0.013358
23279,2018-08-27,UNH,261.92,267.08,267.45,264.42,265.00,2614000.0,2018-08-27,2018-08-27,-0.000559
23280,2018-08-28,UNH,263.33,268.51,269.14,267.33,268.54,2603900.0,2018-08-28,2018-08-28,0.003987
23281,2018-08-29,UNH,263.81,269.00,269.32,267.25,268.39,2880600.0,2018-08-29,2018-08-29,-0.004379
23282,2018-08-30,UNH,263.21,268.39,270.17,268.11,269.46,2976300.0,2018-08-30,2018-08-30,0.000000
23283,2018-08-31,UNH,263.28,268.46,269.21,267.20,268.28,2961500.0,2018-08-31,2018-08-31,-0.001044
23284,2018-08-31,UNH,263.28,268.46,269.21,267.20,268.28,2961500.0,2018-09-03,2018-09-03,0.002090
23285,2018-09-04,UNH,263.33,268.51,269.41,266.57,268.00,2097300.0,2018-09-04,2018-09-04,-0.003575
23286,2018-09-05,UNH,262.47,267.64,268.80,266.93,268.56,2230600.0,2018-09-05,2018-09-05,0.007623
23287,2018-09-06,UNH,265.34,269.65,270.02,266.94,267.60,2556100.0,2018-09-06,2018-09-06,-0.010607
23288,2018-09-07,UNH,263.99,268.28,271.16,267.51,269.64,2958000.0,2018-09-07,2018-09-07,-0.033211
23289,2018-09-10,UNH,255.58,259.73,266.80,258.75,266.78,4146200.0,2018-09-10,2018-09-10,0.012407
23290,2018-09-11,UNH,256.86,261.04,261.42,257.48,257.92,2283300.0,2018-09-11,2018-09-11,0.011642
23291,2018-09-12,UNH,258.47,262.67,264.49,260.85,261.12,2236300.0,2018-09-12,2018-09-12,0.004694

In [44]:
price_data_ffill.to_csv('unagg_ffill_price.csv')

In [40]:
# all_ffill_train = all_ffill[pd.to_datetime(all_ffill['day']) <= datetime.datetime(2017,5,3)]
# all_ffill_validation = all_ffill[(pd.to_datetime(all_ffill['day']) >= datetime.datetime(2017,5,4)) & \
#                                  (pd.to_datetime(all_ffill['day']) <= datetime.datetime(2018,4,4))]
# all_ffill_test = all_ffill[pd.to_datetime(all_ffill['day']) >= datetime.datetime(2018,4,5)]

## Fill by Mean (Deprecated)

In [41]:
# full_data_train = full_data[pd.to_datetime(full_data['day']) <= datetime.datetime(2017,5,3)]
# full_data_validation = full_data[(pd.to_datetime(full_data['day']) >= datetime.datetime(2017,5,4)) & \
#                                  (pd.to_datetime(full_data['day']) <= datetime.datetime(2018,4,4))]
# full_data_test = full_data[pd.to_datetime(full_data['day']) >= datetime.datetime(2018,4,5)]

In [42]:
# for ticker in full_data_train['ticker'].unique():
#     full_data_train.loc[full_data_train['ticker'] == ticker] = full_data_train.loc[full_data_train['ticker'] == ticker]\
#                                                      .fillna(full_data_train.loc[full_data_train['ticker'] == ticker].mean())
#     full_data_validation.loc[full_data_validation['ticker'] == ticker] = \
#                                             full_data_validation.loc[full_data_validation['ticker'] == ticker]\
#                                             .fillna(full_data_validation.loc[full_data_validation['ticker'] == ticker].mean())
#     full_data_test.loc[full_data_test['ticker'] == ticker] = full_data_test.loc[full_data_test['ticker'] == ticker]\
#                                                      .fillna(full_data_test.loc[full_data_test['ticker'] == ticker].mean())

In [43]:
# full_data_train = full_data_train[full_data_train['hour'].isin(np.arange(8, 17))]
# full_data_validation = full_data_validation[full_data_validation['hour'].isin(np.arange(8, 17))]
# full_data_test = full_data_test[full_data_test['hour'].isin(np.arange(8, 17))]

In [44]:
# full_data_train = full_data_train.groupby(['ticker', 'day'], as_index = False).sum().drop('hour', axis = 1)
# full_data_validation = full_data_validation.groupby(['ticker', 'day'], as_index = False).sum().drop('hour', axis = 1)
# full_data_test = full_data_test.groupby(['ticker', 'day'], as_index = False).sum().drop('hour', axis = 1)

In [45]:
# full_data_train['day'] = full_data_train['day'].astype('str')
# full_data_validation['day'] = full_data_validation['day'].astype('str')
# full_data_test['day'] = full_data_test['day'].astype('str')

In [46]:
# price_full_data_train = price_full_data[pd.to_datetime(price_full_data['day']) <= datetime.datetime(2017,5,3)]
# price_full_data_validation = price_full_data[(pd.to_datetime(price_full_data['day']) >= datetime.datetime(2017,5,4)) & \
#                                  (pd.to_datetime(price_full_data['day']) <= datetime.datetime(2018,4,4))]
# price_full_data_test = price_full_data[pd.to_datetime(price_full_data['day']) >= datetime.datetime(2018,4,5)]

In [47]:
# for ticker in price_full_data_train['ticker'].unique():
#     price_full_data_train.loc[price_full_data_train['ticker'] == ticker] = \
#                                              price_full_data_train.loc[price_full_data_train['ticker'] == ticker]\
#                                             .fillna(price_full_data_train.loc[price_full_data_train['ticker'] == ticker].mean())
#     price_full_data_validation.loc[price_full_data_validation['ticker'] == ticker] = \
#                                  price_full_data_validation.loc[price_full_data_validation['ticker'] == ticker]\
#                                  .fillna(price_full_data_validation.loc[price_full_data_validation['ticker'] == ticker].mean())
#     price_full_data_test.loc[price_full_data_test['ticker'] == ticker] = \
#                                              price_full_data_test.loc[price_full_data_test['ticker'] == ticker]\
#                                             .fillna(price_full_data_test.loc[price_full_data_test['ticker'] == ticker].mean())

In [48]:
# price_full_data_train['open_price_change'] = price_full_data_train['open'] - price_full_data_train['open'].shift(1)
# price_full_data_validation['open_price_change'] = price_full_data_validation['open'] - \
#                                                   price_full_data_validation['open'].shift(1)
# price_full_data_test['open_price_change'] = price_full_data_test['open'] - price_full_data_test['open'].shift(1)

In [49]:
# all_fillmean_train = full_data_train.merge(price_full_data_train, how = 'left', on = ['ticker', 'day'])
# all_fillmean_validation = full_data_validation.merge(price_full_data_validation, how = 'left', on = ['ticker', 'day'])
# all_fillmean_test = full_data_test.merge(price_full_data_test, how = 'left', on = ['ticker', 'day'])

In [50]:
# all_fillmean_train = all_fillmean_train[all_fillmean_train['day'] != '2014-01-02']
# all_fillmean_validation = all_fillmean_validation[all_fillmean_validation['day'] != '2014-01-02']
# all_fillmean_test = all_fillmean_test[all_fillmean_test['day'] != '2014-01-02']

In [51]:
# all_fillmean_train.to_csv('fillmean_train.csv')
# all_fillmean_validation.to_csv('fillmean_validation.csv')
# all_fillmean_test.to_csv(
#     'fillmean_test.csv')